export const techIcons: Record<string, string> = {
  React: "/icons/react.png",
  Vue: "/icons/vue.png",
  "Next.js": "/icons/nextjs.png",
  TypeScript: "/icons/typescript.png",
  "Tailwind CSS": "/icons/tailwindcss.png",
  Zustand: "/icons/zustand.png",
  Supabase: "/icons/supabase.png",
  Unity: "/icons/unity.png",
  "C#": "/icons/csharp.png",
  Python: "/icons/python.png",
  WebSocket: "/icons/websocket.png",
  Flask: "/icons/flask.png",
  AWS: "/icons/aws.png",
  "Spring Boot": "/icons/springboot.png",
  MySQL: "/icons/mysql.png",
  MariaDB: "/icons/mariadb.png",
  Redux: "/icons/redux.png",
  Docker: "/icons/docker.png",
  K8S: "/icons/k8s.png",
};
